# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration


[changelog]
# A Tera template to be rendered for each release in the changelog.
# See https://keats.github.io/tera/docs/#introduction

# template for the changelog header
header = """
# Changelog

Im nachfolgenden werden alle Änderungen gelistet.

"""

# template for the body
body = """
{% if version %}\
    ## [{{ version }}](<REPO>/tree/{{ version| urlencode }}/) - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unversioniert](<REPO>/tree/main)
{% endif %}\
{% if previous %}\
    {% if previous.version and version %}\

    [Änderungen {{ previous.version }} &rarr; {{ version }}](<REPO>/-/compare?from={{ previous.version | urlencode }}&to={{ version | urlencode }})
    {% elif previous.version %}\

    [Änderungen seit {{ previous.version }}](<REPO>/-/compare?from={{ previous.version | urlencode }}&to=main)
    {% endif %}\
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
            {% if commit.breaking %}[**breaking**] {% endif %}\
            {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](<REPO>/commit/{{ commit.id }}))\
            {% for footer in commit.footers -%}
              {% if footer.separator | trim == "#" and footer.value is matching("^[0-9]+$")-%}
                , {{ footer.token }} [{{ footer.separator | trim }}{{ footer.value }}](<REPO>/issues/{{ footer.value }})
              {%- else -%}
                , {{ footer.token }}{{ footer.separator }}{{ footer.value }}\
              {%- endif -%}\
            {% endfor %}\
    {% endfor %}
{% endfor %}\n
"""

# template for the changelog footer
footer = """
<!-- generated by git-cliff -->
"""

# Remove leading and trailing whitespaces from the changelog's body.
trim = true
# Render body even when there are no releases to process.
render_always = true
# An array of regex based postprocessors to modify the changelog.
postprocessors = [
    # Replace the placeholder <REPO> with a URL.
    { pattern = '<REPO>', replace = "https://github.com/BBBaden/uteam-swdev-docs" },
]
# render body even when there are no releases to process
# render_always = true
# output file path
# output = "test.md"

[git]
# Parse commits according to the conventional commits specification.
# See https://www.conventionalcommits.org
conventional_commits = true
# Exclude commits that do not match the conventional commits specification.
filter_unconventional = true
# Require all commits to be conventional.
# Takes precedence over filter_unconventional.
require_conventional = false
# Split commits on newlines, treating each line as an individual commit.
split_commits = false
# An array of regex based parsers to modify commit messages prior to further processing.
commit_preprocessors = [
    # Replace issue numbers with link templates to be updated in `changelog.postprocessors`.
    #{ pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](<REPO>/issues/${2}))"},
    # Check spelling of the commit message using https://github.com/crate-ci/typos.
    # If the spelling is incorrect, it will be fixed automatically.
    #{ pattern = '.*', replace_command = 'typos --write-changes -' },
]
# Prevent commits that are breaking from being excluded by commit parsers.
protect_breaking_commits = false

# An array of regex based parsers for extracting data from the commit message.
# Assigns commits to groups.
# Optionally sets the commit's scope and can decide to exclude commits from further processing.
commit_parsers = [
  { message = "^(n|neu):", group = "<!-- 0 -->✨ Neu hinzugefügt" },
  { message = "^(k|korrektur):", group = "<!-- 1 -->🐛 Korrekturen" },
  { message = "^(c|change):", group = "<!-- 2 -->♻️ Geändert" },
  { message = "^(e|entfernt):", group = "<!-- 3 -->❌ Entfernt" },
  { message = "^(t|tool):", group = "<!-- 4 -->🛠️ Tooling" },
  { message = "^(h|housekeeping):", group = "<!-- 5 -->🧹 Aufräumen" },
  { message = "^(s|sonstiges):", group = "<!-- 6 -->⚙️ Sonstiges" },
]

# Exclude commits that are not matched by any commit parser.
filter_commits = false
# Fail on a commit that is not matched by any commit parser.
fail_on_unmatched_commit = false
# An array of link parsers for extracting external references, and turning them into URLs, using regex.
link_parsers = []
# Include only the tags that belong to the current branch.
use_branch_tags = false
# Order releases topologically instead of chronologically.
topo_order = false
# Order commits topologically instead of chronologically.
topo_order_commits = true
# Order of commits in each group/release within the changelog.
# Allowed values: newest, oldest
sort_commits = "oldest"
# Process submodules commits
recurse_submodules = false
